### ISSUE TITLE
ICMとArduinoの通信状態が取得できない

### ISSUE THREAD

**Issue by MasatoKubotera** [SUSTAINA-OP/IMU-Measurement-and-Transmission-Module#10]
ICM42688から最新のデータを読み取り，バッファに保存に保存する際，ICMとArduinoが通信できない状態でもエラー（return < 0）とならなく，通信状態が取得できていない．

https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/3bd0b7465cd74c2477f245b46132e8cdf462dd83/firmware/src/ICM42688.cpp#L280-L301

**Comment by MasatoKubotera** [comment]
IMUモジュールを抜いた状態で，getAGT()を叩いた時の戻り値は1．

この時に取得した，加速度（ｘ，ｙ，ｚ），ジャイロ（ｘ，ｙ，ｚ），温度は以下のようになった．
[-0.000244140625, -0.000244140625, -0.000244140625, -0.030517578125, -0.030517578125, -0.030517578125, 24.99245262145996]

Arduino起動時からモジュールを抜いた場合，begin()の戻り値は-3となった．通常時の戻り値は1．

**Comment by MasatoKubotera** [comment]
readRegistersのところにSPI接続の場合，return < 0とは仕様的にならない．

https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/3bd0b7465cd74c2477f245b46132e8cdf462dd83/firmware/src/ICM42688.cpp#L636-L668

**Comment by MasatoKubotera** [comment]
I２C接続において，
IMUモジュールを抜いた状態で，getAGT()を叩いた時の戻り値は-1となった．

この時に取得した，加速度（ｘ，ｙ，ｚ），ジャイロ（ｘ，ｙ，ｚ），温度は以下のようになった．
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

Arduino起動時からモジュールを抜いた場合，begin()の戻り値は-3となった．通常時の戻り値は1．

**Comment by MasatoKubotera** [comment]
https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/issues/10#issuecomment-1784825699

SPIでの接続時，readRegistersからerror値が帰ってくるようにしないとだめそう．

**Comment by hiroki-0001** [comment]
こちら調査しましたが、Arduino の I2C通信にはデータの送受信を行う前にデータの送受信回数(ICM42688の場合は加速度3 + ジャイロ3 + 温度1 で合計7)があっているかどうか確認する関数が存在します。`_i2c->requestFrom(_address, count)`

これを用いることでI2C通信の場合は通信中にデバイスとの接続不良が起こっても、即座に検知し、errorを吐き出すことができています。

しかし、SPI通信の場合はそういった関数がArduinoのライブラリに実装されていません。
https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/SPI/SPI.cpp

公式ライブラリを改造するという手法を用いればいけなくもなさそうですがめんどくさそうです。
(以下の関数の一部を変更すればいけるかも？)
https://github.com/arduino/ArduinoCore-samd/blob/84c09b3265e2a8b548a29b141f0c9281b1baf154/cores/arduino/SERCOM.cpp#L329-L339

またSPI通信で接続のエラー検知をする場合は前述した公式ライブラリの改造以外にも、手段はあります。
それは、ICM42688のSPI通信のread/write時に一番最初に行う通信の受信値を見る方法です。

[ICM42688のデータシート](https://product.tdk.com/system/files/dam/doc/product/sensor/mortion-inertial/imu/data_sheet/ds-000347-icm-42688-p-v1.6.pdf)のp.53にspi通信のコミュニケーションについて記載されてあります。

具体的な実装方法として考えているのは、毎回spi通信のデータを読み取るの際(read処理)にはArduinoのSPI.hの`transfer()`関数を用いて通信を行いますが、一番はじめに行う`transfer()`の返り値を確認します。この返り値はIMUの取得したセンサ値のように変動する値ではなく、おそらく固定の値だと考えられます。(データの送受信を行う最初の合図のような通信のため)

ただ厄介なのが、この一番始めに行う`transfer()`の通信エラーの時の返り値の定義がどのドキュメントを見ても書かれておらず、どのような返り値のときは通信エラーだということがまだわかっていません。(おそらく0以外の値だとは考えられるが・・・)

これらの点から、今回の問題を解決する最短手順はI2C通信を使用することだと考えています。

**Comment by MasatoKubotera** [comment]
今後の対応

>これらの点から、今回の問題を解決する最短手順はI2C通信を使用することだと考えています。

1. SPIとI2Cにおける ICM <-> Arduino間の通信速度の計測
シングルボードコンピュータが200Hzで値欲求してくるので十分な応答速度であるか検証
2. PCBにプルアップ抵抗を実装する必要があるかを検討
3.現状のPCBをSPIからI2C仕様に変更できるかの検討

**Comment by MasatoKubotera** [comment]
IMUとマイコンのSPI通信でもWho Am Iを利用することで状態を確認することができる．
接続されていない場合，if(whoAmI() != WHO_AM_I)がfalseとなる．

https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/3bd0b7465cd74c2477f245b46132e8cdf462dd83/firmware/src/ICM42688.cpp#L88-L91

https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/3bd0b7465cd74c2477f245b46132e8cdf462dd83/firmware/src/ICM42688.cpp#L689-L698

この検証にかかる処理時間は，以下の関数を新たに設立して，**36.58 us**となった．
```.cpp
bool ICM42688::getWhoAmI() {
  // check the WHO AM I byte
  if(whoAmI() != WHO_AM_I) {
    return false;
  }
  return true;
}
```

参考値として，getAGT()の処理時間は，**138.236 us**であった．

シングルボードコンピュータから200 Hzで値要求しても十分な応答速度であるため，SPI通信の状態検出（接続，未接続）判定は，WhoAmIが利用できる．

WhoAmIの問題点としては，値取得と同時の通信状態を獲得できないことである．

**Comment by MasatoKubotera** [comment]
Who Am Iを毎ループ事に実行し，返答を確認することで接続状態を得ることができるようした．

毎ループ事の再接続
https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/a4f66178149d63f8f5228e6769e0eedebfebed6d/firmware/firmware.ino#L78-L82

再接続後のエラー処理
https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/a4f66178149d63f8f5228e6769e0eedebfebed6d/firmware/firmware.ino#L203-L206

※Who Am Iでのエラー検出目的は，Begin関数実行時には接続されていて，その後通信が途絶えたことを検出するため．Begin関数では，内部にWho Am Iが実装されており，通信できない場合はBegin関数でエラーを返す．

追加したWho Am I関数
https://github.com/SUSTAINA-OP/IMU-Measurement-and-Transmission-Module/blob/a4f66178149d63f8f5228e6769e0eedebfebed6d/firmware/src/ICM42688/ICM42688.cpp#L700-L706


問題点として，値取得と同時に通信状態を確認できないが，数百μの周期において無視できるレベルと判断する．
